#@package _global_
mephisto:
  blueprint:
    onboarding_qualification: turn_annotations
  task:
    allowed_concurrent: 1
    maximum_units_per_worker: 3
    task_description: |
      <b><h4>Task Description</h4></b>
      <br>
      Dummy Task Description.

      Lorem ipsum.
      <br><br>
    task_name: turn_annotations
    task_reward: 0.3
    task_tags: "chat,conversation,dialog,partner"
    task_title: "Chat with a fellow conversationalist!"
mturk:
  worker_blocklist_paths: null
