#@package _global_
mephisto:
  blueprint:
    acute_eval_type: engaging
    config_path: ${task_dir}/task_config/model_config.json
    models: model1,model2
    num_self_chats: 100
    root_dir: ${task_dir}/_test_output_folder
    onboarding_path: ${task_dir}/task_config/onboarding.json
    task: blended_skill_talk
